---
title: "Reproduciblity technical replicates"
output: html_notebook
---

```{r}
pro_10x <- function(.x){
    matr <- Read10X(.x)
    gene <- readr::read_rds("/home/pauling/projects/02_data/09_Gene/coding_gene.rds.gz")
    over_gene <- intersect(gene$gene_name, rownames(matr))
    matr <- matr[over_gene,]
    matr <- as.matrix(matr)
    matr <- t(matr)
    return(matr)
}
pro_10x_mouse <- function(.x){
    matr <- Read10X(.x)
    gene <- readr::read_rds("/home/pauling/projects/02_data/09_Gene/mouse/protein_coding.rds.gz")
    over_gene <- intersect(gene$gene_name, rownames(matr))
    matr <- matr[over_gene,]
    matr <- as.matrix(matr)
    matr <- t(matr)
    return(matr)
}
```

```{r}
#GSE65525 indrop mESC
mda1 <- readr::read_rds("/home/pauling/projects/04_SEmodel/01_data/05_Gene_Selection_Benchmark/02_Reproducibility/mESC_replicates/mda.rds.gz")
```

#PBMC 1k
```{r}
path_1 <- "/home/pauling/projects/04_SEmodel/01_data/05_Gene_Selection_Benchmark/02_Reproducibility/02_pbmc/V3_matrix"
path_2 <- "/home/pauling/projects/04_SEmodel/01_data/05_Gene_Selection_Benchmark/02_Reproducibility/02_pbmc/V3_2_matrix/"

matr1 <- pro_10x(path_1)
matr2 <- pro_10x(path_2)
```

#brain
```{r}
path_1 <- "/home/pauling/projects/04_SEmodel/01_data/05_Gene_Selection_Benchmark/02_Reproducibility/03_brain/brain_1k/"
path_2 <- "/home/pauling/projects/04_SEmodel/01_data/05_Gene_Selection_Benchmark/02_Reproducibility/03_brain/brain_10k/"

brain.matr1 <- pro_10x_mouse(path_1)
brain.matr2 <- pro_10x_mouse(path_2)
```

#heart
```{r}
path_1 <- "/home/pauling/projects/04_SEmodel/01_data/05_Gene_Selection_Benchmark/02_Reproducibility/04_heart/heart_1k/"
path_2 <- "/home/pauling/projects/04_SEmodel/01_data/05_Gene_Selection_Benchmark/02_Reproducibility/04_heart/heart_10k/"

heart.matr1 <- pro_10x_mouse(path_1)
heart.matr2 <- pro_10x_mouse(path_2)
```

```{r}
tibble(
  tissue = c("mESC","mESC","PBMC","PBMC","brian","brain","heart","heart"),
  expr = list(mda1$matr[[1]], mda1$matr[[2]], matr1, matr2, brain.matr1, brain.matr2, heart.matr1, heart.matr2)
) -> cda

cda %>%
  dplyr::mutate(
    expr = purrr::map(
      .x = expr,
      .f = function(.x){
        .x <- matr_filter(.x, min.cells = 10)
        .x <- as.matrix(.x)
        return(.x)
      }
    )
  ) -> cda

cda %>%
  dplyr::mutate(
    res = purrr::map(
      .x = expr,
      .f = function(.x){
        Res1 <- SE_fun(.x)
        m1 <- m3d_fun(.x)
        HVG1 <- HVG_fun(.x)
        G1 <- Gini_fun(.x)
        list(Res1, m1, HVG1, G1)
      }
    )
  ) -> cda

cda <- readr::read_rds("/home/pauling/projects/04_SEmodel/05_data_phase2/01.gene.selection.benchmark/04.reproducibility/cda.rds.gz")
```

```{r, fig.width=6, fig.height=4}
tissue <- c("mESC","PBMC","brian","heart")
out.path <- "/home/pauling/projects/04_SEmodel/04_figures/04_DE.benchmark/01.DE.benchmark/03.Reproducibility"
for (i in 1:4) {
    tibble(
        ID = rep(c(1:4),4),
        gene_num = c(rep(500,4),rep(1000,4),rep(1500,4),rep(2000,4)),
        method = rep(c("SEM","M3Drop","HVG","Gini"),4)
    ) %>%
        dplyr::mutate(
            Reproducibility = purrr::map2_dbl(
                .x = ID,
                .y = gene_num,
                .f = function(.x, .y){
                  if(.x == 3){
                    cda$res[[2*i-1]][[.x]] <- cda$res[[2*i-1]][[.x]] %>% dplyr::arrange(q.value)
                    cda$res[[2*i]][[.x]] <- cda$res[[2*i]][[.x]] %>% dplyr::arrange(q.value)
                  }
                    round(length(intersect(cda$res[[2*i-1]][[.x]]$Gene[1:.y],cda$res[[2*i]][[.x]]$Gene[1:.y]))/.y,2)*100
                }
            )
        ) -> res1
    
    res1 %>%
        ggplot(aes(factor(method, levels = c("SEM","M3Drop","HVG","Gini")), Reproducibility)) +
        geom_polygon(aes(colour = factor(gene_num), group = factor(gene_num)), fill = NA, lwd = 0.8) +
        geom_point(aes(colour = factor(gene_num), fill = factor(gene_num)), shape = 21, alpha = 0.5, size = 3) +
        coord_radar() +
        theme_minimal() +
        theme(axis.text = element_text(size = 12, colour = "black"),
              axis.title = element_text(size = 13, colour = "black"),
        ) +
        labs(
            x = ""
        ) +
      ylim(0, NA) -> p
    ggsave(plot = p, filename = paste0(tissue[i],".pdf"), path = out.path, width = 6, height = 4)
}
```

