---
title: "R Notebook"
output: html_notebook
---

# load data
```{r}
matr1 <- readr::read_rds("/home/pauling/projects/04_SEmodel/01_data/04_rogue/10_batch/matr1_con.rds.gz")
matr2 <- readr::read_rds("/home/pauling/projects/04_SEmodel/01_data/04_rogue/10_batch/matr2_sti.rds.gz")

info <- readr::read_tsv("/home/pauling/projects/04_SEmodel/01_data/04_rogue/10_batch/nbt.4096-S3.txt")
mda <- rbind(matr1, matr2)
```

```{r}
info <- info %>% dplyr::filter(Cell_Name %in% rownames(mda))
info$Cluster_ID <- stringr::str_replace(info$Cluster_ID, " ", "_")
clusters <- unique(info$Cluster_ID)
clusters <- clusters[-c(1,3)]
```

```{r}
patient.rogue <- function(info, condition, cluster, remove.batch = F){
    tmp <- info %>% dplyr::filter(Stim_Condition %in% condition) %>% dplyr::filter(Cluster_ID == cluster)
    patients <- unique(tmp$Patient)
    rogue <- c()
    if(isFALSE(remove.batch)){
        for (i in 1:length(patients)) {
            print(i)
            index1 <- tmp %>% dplyr::filter(Patient == patients[i]) %>% dplyr::pull(Cell_Name)
            if(length(index1) >= 20){
              tmp.matr <- mda[index1,]
              tmp.res <- SE_fun(tmp.matr, r = 1, span = 0.5)
              rogue[i] <- cal_rogue(tmp.res)
            }
            else{
              rogue[i] <- NA
            }
        }
    }
    if(isTRUE(remove.batch)){
      batches <- unique(info$Stim_Condition)
      for (i in 1:length(patients)) {
        print(i)
        tmp.rogue <- c()
        flag <- c()
        for (j in 1:length(batches)) {
          index1 <- tmp %>% 
            dplyr::filter(Patient == patients[i]) %>% 
            dplyr::filter(Stim_Condition == batches[j]) %>%
            dplyr::pull(Cell_Name)
          
          if(length(index1) >= 20){
            flag[j] <- 1
          }
          else{
            flag[j] <- 0
          }
          
          if(flag[j] == 1){
            tmp.matr <- mda[index1,]
            tmp.res <- SE_fun(tmp.matr, r = 1, span = 0.5)
            tmp.rogue[j] <- cal_rogue(tmp.res)
          }
          else{
            tmp.rogue[j] <- NA
          }
          
        }
        
        if(c(flag[1] == 1 & flag[2] == 1)){
          rogue[i] <- mean(tmp.rogue)
        }
        else{
          rogue[i] <- NA
        }
        
        }
    }
    return(rogue)
}
all.p <- list()
for (i in 1:length(clusters)) {
    ctrl <- patient.rogue(info, "ctrl", clusters[i])
    stim <- patient.rogue(info, "stim", clusters[i])
    comb <- patient.rogue(info, c("ctrl","stim"), clusters[i])
    comb.rogue.corrected <- patient.rogue(info, c("ctrl","stim"), clusters[i], remove.batch = T)
    
    tibble(
        ctrl = ctrl,
        stim = stim,
        comb = comb,
        comb.corrected = comb.rogue.corrected,
        patient = 1:length(comb.rogue.corrected)
    ) %>%
        dplyr::filter(!is.na(comb.corrected)) %>%
        tidyr::gather(key = "Condition", value = "ROGUE", -patient) %>%
        ggplot(aes(factor(Condition, levels = c("ctrl","stim","comb","comb.corrected")), ROGUE)) +
        geom_boxplot(color = "#1979B5", outlier.shape = NA) +
        geom_point(color = "#1979B5", size = 1.5) +
        theme_bw() +
        theme(axis.text = element_text(size = 12, colour = "black"),
              axis.title = element_text(size = 13, colour = "black")) +
        labs(
            x = "Condition",
            y = "ROGUE"
        ) -> all.p[[i]]
}
for (i in 2:10) {
  ggsave(paste0(clusters[i],"stim.pdf"), plot = all.p[[i]], width = 5, height = 5, units = "in",
         path = "/home/pauling/projects/04_SEmodel/04_figures/05_ROGUE/02.technical.factors")
}
```


```{r}
ctrl.rogue <- patient.rogue(info, "ctrl", "T_activated")
stim.rogue <- patient.rogue(info, "stim", "T_activated")
comb.rogue <- patient.rogue(info, c("ctrl","stim"), "T_activated")
comb.rogue.corrected <- patient.rogue(info = info, condition = c("ctrl","stim"), cluster = "T_activated", remove.batch = T)
```

```{r}
t.test(ctrl.rogue, comb.rogue)
```


```{r}
ctrl.rogue2 <- patient.rogue(info, "ctrl", "CD4 Memory T")
stim.rogue2 <- patient.rogue(info, "stim", "CD4 Memory T")
comb.rogue2 <- patient.rogue(info, c("ctrl","stim"), "CD4 Memory T")
comb.rogue.corrected2 <- patient.rogue(info = info, condition = c("ctrl","stim"), cluster = "CD4 Memory T", remove.batch = T)
```

```{r}
ctrl.rogue3 <- patient.rogue(info, "ctrl", "CD16 Mono")
stim.rogue3 <- patient.rogue(info, "stim", "CD16 Mono")
comb.rogue3 <- patient.rogue(info, c("ctrl","stim"), "CD16 Mono")
comb.rogue.corrected3 <- patient.rogue(info = info, condition = c("ctrl","stim"), cluster = "CD16 Mono", remove.batch = T)
```


```{r, fig.width=5, fig.height=5}
tibble(
  ctrl = ctrl.rogue2,
  stim = stim.rogue2,
  comb = comb.rogue2,
  comb.corrected = comb.rogue.corrected2,
  patient = 1:length(ctrl.rogue)
) %>%
  tidyr::gather(key = "Condition", value = "ROGUE", -patient) %>%
  ggplot(aes(factor(Condition, levels = c("ctrl","stim","comb","comb.corrected")), ROGUE)) +
  geom_boxplot(color = "#1979B5", outlier.shape = NA) +
  geom_point(color = "#1979B5", size = 1.5) +
  theme_bw() +
  theme(axis.text = element_text(size = 12, colour = "black"),
        axis.title = element_text(size = 13, colour = "black")) +
  labs(
    x = "Condition",
    y = "ROGUE"
  )
```

