---
title: "R Notebook"
output: html_notebook
---


#ZINB plot
```{r}
file_path <- "/home/pauling/projects/04_SEmodel/01_data/04_rogue/09_simulation_rogue/01.vary.gene/01.NB/"
files <- list.files(file_path)
p <- list()
for (i in 1:length(files)) {
  res <- readr::read_rds(file.path(file_path,files[i]))
  res <- res %>% dplyr::filter(prop > 0.002)
  ggplot(res, aes(x = factor(prop*100), y = rogue)) + 
    geom_boxplot(color = "#1979B5", 
                 fill = "#1979B5",
                 outlier.colour = "black", 
                 outlier.shape = 1) + 
    theme_bw() +
    theme(axis.text = element_text(size = 12, colour = "black"),
          axis.title = element_text(size = 13, colour = "black")) +
    labs(
      x = "Vary x% of genes",
      y = "ROGUE"
    )-> p_boxplot

  dat <- ggplot_build(p_boxplot)$data[[1]]
  dat$xsp <- 1/2 * (dat$xmax + dat$xmin) - 1/4 * (dat$xmax - dat$xmin)
  dat$xep <- 1/2 * (dat$xmax + dat$xmin) + 1/4 * (dat$xmax - dat$xmin)
  p_boxplot +
    geom_segment(data = dat,  aes(x = xmin, xend = xmax, y = middle, yend = middle), colour = "#2BA147", size = 1) +
    geom_segment(data = dat,  aes(x = xsp, xend = xep, y = ymin, yend = ymin), colour = "black", size = 1) +
    geom_segment(data = dat,  aes(x = xsp, xend = xep, y = ymax, yend = ymax), colour = "black", size = 1) -> p[[i]]
}
```

```{r, fig.width=10, fig.height=6}
ggarrange(plotlist = p, ncol = 3, nrow = 2)
```

#Cell Number
```{r}
gene_means <- exp(rnorm(2000, 0, sd = 2))
sim.matr <- simul_da(gene_means, r = 6, n_gene = 2000, n_cell = 2000, ZINB = T)
tibble(cell_num = c(20,30,50,100,200,500,1000)) %>%
  dplyr::mutate(
    ent = purrr::map(
      .x = cell_num,
      .f = function(.x){
        print(.x)
        cn <- .x
        tibble(rep = 1:50) %>%
          dplyr::mutate(
            ent = purrr::map(
              .x = rep,
              .f = function(.x){
                tmp_matr <- sim.matr[sample(nrow(sim.matr), cn),]
                ent <- SE_fun(tmp_matr, span = 0.3)
                return(ent)
              }
            )
          )
        
      }
    )
  ) -> cnr

#cnr <- cnr %>% dplyr::mutate(plot = purrr::map(ent, SEplot))
ent.res <- SE_fun(sim.matr)
cnr.pro <- cnr %>% 
  dplyr::mutate(
    ent = purrr::map(
      .x = ent, 
      function(.x){
        .x %>%
          dplyr::mutate(
            cor = purrr::map_dbl(
              .x = ent,
              .f = function(.x){
                a <- .x %>% dplyr::select(Gene, entropy) %>% dplyr::inner_join(ent.res[,c("Gene","entropy")], by = "Gene")
                cor(a$entropy.x, a$entropy.y)
              }
            )
          )
      }
    )
  )

res2 <- Reduce(rbind, cnr.pro$ent) %>%
  dplyr::mutate(cell_num = c(rep(20,50),rep(50,50),rep(100,50),rep(200,50),rep(500,50),rep(1000,50))) %>%
  dplyr::mutate(Sim = "ZINB")

res1 %>%
    dplyr::bind_rows(res2) %>%
    ggplot(aes(factor(cell_num), cor)) +
    geom_boxplot(aes(colour = Sim), outlier.shape = NA) +
    geom_point(aes(group = Sim, colour = Sim), position = position_jitterdodge(jitter.width = 0.15), size = 0.5) +
    theme_bw() +
    theme(
        #legend.position = 'none',
        axis.title = element_text(size = 12,color="black"),
        axis.text = element_text(size = 12,color="black"),
        legend.title = element_text(size =12),
        legend.text = element_text(size = 12),
        axis.text.y = element_text(color="black"),
        axis.text.x = element_text(color="black")
    ) +
    labs(
        x = "Number of cells",
        y = "Pearson correlation"
    ) +
  scale_color_manual(values = c("#FF3E96", "#00868B"))

#c("#D02090", "#FF3E96", "#00E5EE", "#00C5CD", "#00868B")
```

```{r}
res1 <- Reduce(rbind, cnr.pro1$ent) %>%
  dplyr::mutate(cell_num = c(rep(20,50),rep(50,50),rep(100,50),rep(200,50),rep(500,50),rep(1000,50))) %>%
  dplyr::mutate(Sim = "NB")

    ggplot(aes(factor(cell_num), cor)) +
    geom_boxplot(outlier.colour = "white") +
    geom_jitter(width = 0.1, size = 0.7) +
    theme_bw() +
    theme(
        legend.position = 'none',
        axis.title = element_text(size = 12,color="black"),
        axis.text = element_text(size = 12,color="black"),
        legend.title = element_text(size =12),
        legend.text = element_text(size = 12),
        axis.text.y = element_text(color="black"),
        axis.text.x = element_text(color="black")
    ) +
    labs(
        x = "Number of cells",
        y = "Pearson correlation"
    )
```

