---
title: "R Notebook"
output: html_notebook
---


```{r, fig.width=5, fig.height=4}
res <- list()

fc <- c(2,5,20,50,70,100)
for (j in 1:length(fc)) {
  rg <- c()
  si <- c()
  
  for (i in 1:50) {
    print(i)
    gene_mean <- rnorm(10000, 0, sd = 2)
    gene_mean <- exp(gene_mean)
    sda1 <- simul_da(gene_mean, r = 6, n_gene = 400, n_cell = 400)
    sda2 <- simul_da(gene_mean*fc[j], r = 6, n_gene = 400, n_cell = 400)
    sda <- rbind(sda1, sda2)
    ent_res <- SE_fun(sda, span = 0.1, r = 0.01)

    rg[i] <- cal_rogue(ent_res)
    pca.data <- prcomp(sda, center=TRUE)
    dd <- dist(pca.data$x)
    a <- summary(silhouette(c(rep(0,400), rep(1,400)), dd))
    si[i] <- a$avg.width
  }
  tmp.res <- tibble(rg = rg, si = si, fc = fc[j])
  res[[j]] <- tmp.res
}

res[[6]] %>%
  ggplot(aes(si, rg)) +
  geom_point(colour = "#66BECD") +
  xlim(0.6,0.75) +
  ylim(0.97,1) +
  theme_bw() +
  theme(axis.text = element_text(size = 12, colour = "black"),
        axis.title = element_text(size = 13, colour = "black")) +
  labs(
    x = "Silhouette",
    y = "ROGUE"
  ) -> p6

ggarrange(p1,p2,p3,p4,p5,p6, ncol = 3)
```

```{r}
gene_mean <- rnorm(10000, 0, sd = 2)
gene_mean <- exp(gene_mean)
sda1 <- simul_da(gene_mean, r = 6, n_gene = 400, n_cell = 400)
sda2 <- simul_da(gene_mean*10, r = 6, n_gene = 400, n_cell = 400)
```

```{r, fig.width=5, fig.height=4}
total_umi <- rowSums(sda1)
total_umi2 <- rowSums(sda2)

tibble(
  batch1 = total_umi,
  batch2 = total_umi2
) %>%
  tidyr::gather(key = "batch", value = "Total.UMI.counts") %>%
  ggplot(aes(Total.UMI.counts)) +
  geom_histogram(binwidth = 0.02, aes(fill = batch), colour = "black", lwd = 0.1) +
  theme_bw() +
  theme(
    axis.title = element_text(size = 15,color="black"),
    axis.text = element_text(size = 15,color="black"),
    legend.title = element_text(size = 0),
    legend.text = element_text(size = 0),
    axis.text.y = element_text(color="black"),
    axis.text.x = element_text(color="black")
  ) +
  labs(
    x = "Total cell UMI",
    y = "Number of cells"
  ) +
  scale_x_log10() +
  scale_fill_manual(values = c("#B0E2FF", "#FFEBCD"))
```

