---
title: "R Notebook"
output: html_notebook
---

```{r}
load("/data1/et/muris/facs/FACS_all.Robj")
muris.matr <- tiss_FACS@data
muris.matr <- exp(muris.matr) - 1
muris.matr <- t(muris.matr)
ent.res <- SE_fun(as.matrix(muris.matr), r = 1)

readr::write_rds(muris.matr, "/home/pauling/projects/02_data/06_mouse/facs.matr.rds.gz", compress = "gz")
```


```{r}
a <- readr::read_tsv("/home/pauling/projects/04_SEmodel/01_data/09_DC_immunity/GSE127465_human_cell_metadata_54773x25.tsv.gz")
a <- a %>% dplyr::filter(stringr::str_detect(`Minor subset`, "DC"))
```

```{r}
matr <- readr::read_rds("/home/pauling/projects/04_SEmodel/01_data/04_rogue/02_cell_type_validation/02_DC/DC_matr.rds.gz")
meta <- readr::read_rds("/home/pauling/projects/04_SEmodel/01_data/04_rogue/02_cell_type_validation/02_DC/DC_meta.rds.gz")
```

```{r}
meta <- meta %>%
  tidyr::separate(NAME, c("A","B","C","D"), sep = "\\_")
```

```{r, fig.width=6}
gene <- readr::read_rds("/home/pauling/projects/02_data/09_Gene/coding_gene.rds.gz")
over_gene <- intersect(gene$gene_name, colnames(matr))
matr <- matr[,over_gene]

DCs <- unique(meta$CellType)
ent.all.res <- list()
for (i in 1:6) {
  index5 <- meta %>% dplyr::filter(CellType %in% DCs[i]) %>% dplyr::pull(ID)
  expr <- matr[index5,]
  expr <- matr_filter(expr, min.cells = 3)
  ent.all.res[[i]] <- SE_fun(expr, span = 0.3, r = 0.1)
}
ent_res <- SE_fun(expr, span = 0.5, r = 0.1)
SEplot(ent.all.res[[6]], geom_line = T, p.adj = T)
```

```{r}
for (i in 1:6) {
  print(cal_rogue(ent.all.res[[i]], k = 200))
}
```


```{r}
for (i in 1:6) {
  p <- SEplot(ent.all.res[[i]], p.adj = T)
  png.plot <- p + theme_bw() + 
    theme(legend.position = "NULL") + 
    theme(rect = element_blank(), 
          text = element_blank(), 
          axis.ticks = element_blank())
  
  ggsave(png.plot, filename = "./temp.png", width = 6, height = 4)
  img <- readPNG("./temp.png")
  file.remove("./temp.png")
  blank.plot <- SEplot(ent.all.res[[6]], point_size = -1, p.adj = T)
  range.values <- c(
      ggplot_build(plot = blank.plot)$layout$panel_params[[1]]$x.range,
      ggplot_build(plot = blank.plot)$layout$panel_params[[1]]$y.range
  )
  p <- blank.plot +
      annotation_raster(img, xmin = range.values[1], xmax = range.values[2],
                        ymin = range.values[3], ymax = range.values[4])
  ggsave(filename = paste0(DCs[i], ".pdf"), plot = p, 
         path = "/home/pauling/projects/04_SEmodel/04_figures/05_ROGUE/01.pure.DC", 
         width = 6, height = 4, units = "in")
}
```

